name: Delete Resources

on:
    workflow_dispatch:

jobs:
  delete-resources:
    runs-on: ubuntu-latest
    env:
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        API_KEY: ${{secrets.API_KEY}}
        NBA_ENDPOINT: ${{secrets.NBA_ENDPOINT}}
        GLUE_DATABASE_NAME: ${{secrets.GLUE_DATABASE_NAME}}
        AWS_REGION: us-east-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Run create bucket script
      run: python3 delete.py